[project.urls]
Homepage = "https://github.com/nikolay0x7/logind-eventd"
Repository = "https://github.com/nikolay0x7/logind-eventd"
Issues = "https://github.com/nikolay0x7/logind-eventd/issues"

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "logind-eventd"
version = "0.1.0"
description = "Event-driven daemon for systemd-logind"
requires-python = ">=3.13"

dependencies = [
    "dbus-next",
]
